# Generated by Django 2.2.2 on 2019-06-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultos', models.IntegerField(max_length=1)),
                ('niños', models.IntegerField(max_length=1)),
                ('lugar', models.CharField(max_length=2)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Turno', verbose_name='placa dedl auto que se esta registrndo')),
            ],
        ),
    ]
