# Generated by Django 2.2.2 on 2019-06-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='adultos',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='registro',
            name='niños',
            field=models.CharField(max_length=1),
        ),
    ]
