# Generated by Django 2.2.2 on 2019-06-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20190610_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='placa',
            field=models.CharField(max_length=10),
        ),
    ]
