# Generated by Django 2.2.2 on 2019-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20190611_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugarOcupado', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='ventaTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='adultos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='niños',
            field=models.IntegerField(),
        ),
    ]
